import React, {useState} from 'react';
import {Pressable, StyleSheet, Text, View, useWindowDimensions} from 'react-native';
import Svg,{Circle,Line,Path,Text as SvgText} from 'react-native-svg';
import {colors as c, spacing as s, typography as t} from '../../theme';
export function AnalyticsCard({title,description,children,footer}:{title:string;description?:string;children:React.ReactNode;footer?:string}){return <View style={styles.card}><Text style={t.sectionTitle}>{title}</Text>{description&&<Text style={styles.desc}>{description}</Text>}{children}{footer&&<Text style={styles.footer}>{footer}</Text>}</View>}
export function RangeControl({value,onChange}:{value:string;onChange:(v:any)=>void}){return <View style={styles.range}>{(['30D','3M','6M','1Y'] as const).map(x=><Pressable key={x} onPress={()=>onChange(x)} style={[styles.rangeItem,value===x&&styles.rangeSelected]}><Text style={[t.caption,{color:value===x?c.selectedText:c.textSecondary}]}>{x}</Text></Pressable>)}</View>}
function coords(values:(number|null)[],w:number,h:number){const min=0,max=100;return values.map((v,i)=>v===null?null:{x:8+(i/(Math.max(1,values.length-1)))*(w-16),y:h-12-(v-min)/(max-min)*(h-24)});}
export function LineChart({values,color,labels=[],showDots=true}:{values:(number|null)[];color:string;labels?:string[];showDots?:boolean}){const w=Math.max(260,useWindowDimensions().width-64),h=180;const pts=coords(values,w,h);let d='';let open=false;pts.forEach((p)=>{if(!p){open=false;return;} d+=(open?' L ':' M ')+`${p.x} ${p.y}`;open=true;});return <Svg width={w} height={h} accessibilityLabel="Analytics line chart"><Line x1="8" y1="12" x2="8" y2={h-12} stroke="#E4E4DF"/><Line x1="8" y1={h-12} x2={w-8} y2={h-12} stroke="#E4E4DF"/><Path d={d} fill="none" stroke={color} strokeWidth={2}/>{showDots&&pts.map((p,i)=>p&&<Circle key={i} cx={p.x} cy={p.y} r={3.5} fill={color}/>) }{labels.length>0&&<><SvgText x="8" y={h-1} fill="#74746F" fontSize="10">{labels[0]}</SvgText><SvgText x={w-8} y={h-1} fill="#74746F" fontSize="10" textAnchor="end">{labels.at(-1)}</SvgText></>}</Svg>}
export function MultiLineChart({series}:{series:{color:string;values:(number|null)[]}[]}){const w=Math.max(260,useWindowDimensions().width-64),h=180;return <Svg width={w} height={h} accessibilityLabel="Multi activity weekly chart">{series.map((line,j)=>{const pts=coords(line.values,w,h);let d='';let open=false;pts.forEach(p=>{if(!p){open=false;return;}d+=(open?' L ':' M ')+`${p.x} ${p.y}`;open=true;});return <Path key={j} d={d} fill="none" stroke={line.color} strokeWidth={2}/>})}</Svg>}
export function BarChart({items,color}:{items:{label:string;value:number|null;count?:number|string;percentage?:number}[];color?:string}){const max=Math.max(1,...items.map(x=>x.value||0));return <View style={styles.bars}>{items.map((x,i)=><View key={i} style={styles.barRow}><Text style={styles.barLabel}>{x.label}</Text><View style={styles.barTrack}><View style={[styles.barFill,{width:`${((x.value||0)/max)*100}%`,backgroundColor:color||'#1F1F1D'}]}/></View><Text style={styles.barValue}>{x.count??(x.value===null?'—':Math.round(x.value))}</Text>{x.percentage!==undefined&&<Text style={styles.barPercent}>{Math.round(x.percentage)}%</Text>}</View>)}</View>}
export function Heatmap({cells,color}:{cells:{date:string;weight:number|null;label?:string}[];color:string}){const [selected,setSelected]=useState<typeof cells[number]|null>(null);return <View><View style={styles.heatGrid}>{cells.map((x,i)=><Pressable accessibilityLabel={`${x.date}${x.label?`, ${x.label}`:', no entry'}`} key={x.date} onPress={()=>setSelected(x)} style={[styles.cell,{backgroundColor:x.weight===null?'#D7D7D2':color,opacity:x.weight===null?.5:.15+(x.weight/100)*.85}]}/>)}</View>{selected&&<Text style={styles.tooltip}>{selected.date}  {selected.label||'—'}</Text>}</View>}
export function ScatterPlot({points,color}:{points:{x:number;y:number;date?:string}[];color:string}){const w=Math.max(260,useWindowDimensions().width-64),h=180;return <Svg width={w} height={h} accessibilityLabel="Analytics scatter plot"><Line x1="8" y1="12" x2="8" y2={h-12} stroke="#E4E4DF"/><Line x1="8" y1={h-12} x2={w-8} y2={h-12} stroke="#E4E4DF"/>{points.map((p,i)=><Circle key={i} cx={8+(p.x/100)*(w-16)} cy={h-12-(p.y/100)*(h-24)} r={4} fill={color}/>)}</Svg>}
export function Placeholder({children}:{children:string}){return <View style={styles.placeholder}><Text style={styles.placeholderText}>{children}</Text></View>}
const styles=StyleSheet.create({card:{backgroundColor:c.surface,borderColor:c.border,borderWidth:1,borderRadius:16,padding:s.lg,gap:s.sm},desc:{...t.secondary,color:c.textSecondary},footer:{...t.caption,color:c.textSecondary,marginTop:s.sm},range:{flexDirection:'row',backgroundColor:c.surfaceSecondary,borderRadius:10,padding:3,alignSelf:'flex-start'},rangeItem:{paddingVertical:7,paddingHorizontal:12,borderRadius:8},rangeSelected:{backgroundColor:c.selected},bars:{gap:10},barRow:{flexDirection:'row',alignItems:'center',gap:8},barLabel:{width:72,...t.caption,color:c.textPrimary},barPercent:{width:38,textAlign:'right',...t.caption,color:c.textSecondary},barTrack:{flex:1,height:12,backgroundColor:c.surfaceSecondary,borderRadius:6,overflow:'hidden'},barFill:{height:'100%',borderRadius:6},barValue:{width:42,textAlign:'right',...t.caption,color:c.textSecondary},heatGrid:{flexDirection:'row',flexWrap:'wrap',gap:4},cell:{width:16,height:16,borderRadius:4},tooltip:{...t.secondary,color:c.textPrimary,marginTop:s.sm},placeholder:{backgroundColor:c.surfaceSecondary,borderRadius:10,padding:s.lg},placeholderText:{...t.secondary,color:c.textSecondary}});
