import { RatingScaleVersion, parseLocalDate, localDate } from '../domain/task';
import { AnalyticsDataset, AnalyticsEntry, AnalyticsTask, RangeKey, TimelinePoint } from './types';
export const RANGE_DAYS: Record<RangeKey, number> = {'30D':30,'3M':90,'6M':180,'1Y':365};
export const analyticsColors = ['#C96A5A','#5B5BD6','#2A9D8F','#C49335'];
export function rangeDates(endDate: string, range: RangeKey): string[] { const d=parseLocalDate(endDate), n=RANGE_DAYS[range]; return Array.from({length:n},(_,i)=>{const x=new Date(d);x.setDate(d.getDate()-n+1+i);return localDate(x);}); }
function inRange(date:string, dates:Set<string>){return dates.has(date)}
function entriesFor(taskId:string, entries:AnalyticsEntry[], dates?:Set<string>){return entries.filter(e=>e.taskId===taskId && (!dates||inRange(e.localDate,dates))).sort((a,b)=>a.localDate.localeCompare(b.localDate));}
export function getTaskTimeline(taskId:string, entries:AnalyticsEntry[], endDate:string, range:RangeKey):TimelinePoint[]{const dates=rangeDates(endDate,range);const by=new Map(entriesFor(taskId,entries,new Set(dates)).map(e=>[e.localDate,e]));return dates.map(date=>{const e=by.get(date);return e?{date,weight:e.normalizedWeightAtEntry,label:e.optionLabelAtEntry,position:e.positionAtEntry}:{date,weight:null};});}
export function getRollingTrend(taskId:string, entries:AnalyticsEntry[], endDate:string, range:RangeKey, window=7){const timeline=getTaskTimeline(taskId,entries,endDate,range);return timeline.map((p,i)=>{const slice=timeline.slice(Math.max(0,i-window+1),i+1).filter(x=>x.weight!==null) as {weight:number}[];return {date:p.date,value:slice.length>=2?slice.reduce((a,x)=>a+x.weight,0)/slice.length:null,recordedCount:slice.length};});}
export function getCalendarHeatmap(taskId:string,entries:AnalyticsEntry[],endDate:string,range:RangeKey){return getTaskTimeline(taskId,entries,endDate,range).map(p=>({...p,intensity:p.weight===null?0:(p.weight/100)}));}
export function getResponseDistribution(task:AnalyticsTask,entries:AnalyticsEntry[],endDate:string,range:RangeKey){const dates=new Set(rangeDates(endDate,range));const counts=new Map<string,number>();entriesFor(task.id,entries,dates).forEach(e=>counts.set(e.optionId,(counts.get(e.optionId)||0)+1));return task.options.map(o=>({optionId:o.id,label:o.label,position:o.position,count:counts.get(o.id)||0,percentage:0})).map((x,_,a)=>({...x,percentage:a.reduce((n,y)=>n+y.count,0)?x.count/a.reduce((n,y)=>n+y.count,0)*100:0}));}
function weekKey(date:string){const d=parseLocalDate(date);const monday=new Date(d);const day=(monday.getDay()+6)%7;monday.setDate(monday.getDate()-day);return localDate(monday);}
export function getWeeklyTrend(taskId:string,entries:AnalyticsEntry[],endDate:string,range:RangeKey){const dates=new Set(rangeDates(endDate,range));const groups=new Map<string,number[]>();entriesFor(taskId,entries,dates).forEach(e=>{const k=weekKey(e.localDate);(groups.get(k)||groups.set(k,[]).get(k)!).push(e.normalizedWeightAtEntry)});return [...groups].sort().map(([week,values])=>({week,value:values.reduce((a,b)=>a+b,0)/values.length,recordedCount:values.length}));}
export function getMonthlyTrend(taskId:string,entries:AnalyticsEntry[],endDate:string,range:RangeKey){const dates=new Set(rangeDates(endDate,range));const groups=new Map<string,number[]>();entriesFor(taskId,entries,dates).forEach(e=>{const k=e.localDate.slice(0,7);(groups.get(k)||groups.set(k,[]).get(k)!).push(e.normalizedWeightAtEntry)});return [...groups].sort().map(([month,values])=>({month,value:values.reduce((a,b)=>a+b,0)/values.length,recordedCount:values.length}));}
export function getWeekdayPattern(taskId:string,entries:AnalyticsEntry[],endDate:string,range:RangeKey){const dates=new Set(rangeDates(endDate,range));const groups=Array.from({length:7},()=>[] as number[]);entriesFor(taskId,entries,dates).forEach(e=>{const day=(parseLocalDate(e.localDate).getDay()+6)%7;groups[day].push(e.normalizedWeightAtEntry)});return groups.map((v,i)=>({weekday:i,label:['Mon','Tue','Wed','Thu','Fri','Sat','Sun'][i],value:v.length?v.reduce((a,b)=>a+b,0)/v.length:null,recordedCount:v.length}));}
export function getTaskSummary(taskId:string,entries:AnalyticsEntry[],endDate:string,range:RangeKey){const es=entriesFor(taskId,entries,new Set(rangeDates(endDate,range)));return {recordedCount:es.length,latest:es.at(-1),average:es.length?es.reduce((a,e)=>a+e.normalizedWeightAtEntry,0)/es.length:null};}
export function getMultiTaskWeeklyTrend(tasks:AnalyticsTask[],entries:AnalyticsEntry[],endDate:string,range:RangeKey){const weeks=[...new Set(tasks.flatMap(t=>getWeeklyTrend(t.id,entries,endDate,range).map(x=>x.week)))].sort();return weeks.map(week=>({week,series:tasks.map(t=>({taskId:t.id,name:t.name,color:t.color,value:getWeeklyTrend(t.id,entries,endDate,range).find(x=>x.week===week)?.value??null}))}));}
export function getActivityBalance(tasks:AnalyticsTask[],entries:AnalyticsEntry[],endDate:string){const dates=new Set(rangeDates(endDate,'30D'));return tasks.map(t=>{const es=entriesFor(t.id,entries,dates);return {taskId:t.id,name:t.name,color:t.color,value:es.length?es.reduce((a,e)=>a+e.normalizedWeightAtEntry,0)/es.length:null,recordedCount:es.length};});}
export function getCrossTaskWeekdayPattern(tasks:AnalyticsTask[],entries:AnalyticsEntry[],endDate:string,range:RangeKey){return Array.from({length:7},(_,i)=>({weekday:i,label:['Mon','Tue','Wed','Thu','Fri','Sat','Sun'][i],series:tasks.map(t=>{const x=getWeekdayPattern(t.id,entries,endDate,range)[i];return {taskId:t.id,name:t.name,color:t.color,value:x.value};})}));}
export function getPairedEntries(taskA:string,taskB:string,entries:AnalyticsEntry[],lag=0){const a=new Map(entriesFor(taskA,entries).map(e=>[e.localDate,e]));const b=new Map(entriesFor(taskB,entries).map(e=>[e.localDate,e]));const out:{date:string,x:number,y:number}[]=[];for(const [date,e] of a){const d=parseLocalDate(date);d.setDate(d.getDate()+lag);const target=localDate(d), other=b.get(target);if(other)out.push({date,x:e.normalizedWeightAtEntry,y:other.normalizedWeightAtEntry});}return out.sort((x,y)=>x.date.localeCompare(y.date));}
export function getCorrelation(points:{x:number,y:number}[]){if(points.length<2)return null;const mx=points.reduce((a,p)=>a+p.x,0)/points.length,my=points.reduce((a,p)=>a+p.y,0)/points.length;const num=points.reduce((a,p)=>a+(p.x-mx)*(p.y-my),0),dx=Math.sqrt(points.reduce((a,p)=>a+(p.x-mx)**2,0)),dy=Math.sqrt(points.reduce((a,p)=>a+(p.y-my)**2,0));return dx&&dy?num/(dx*dy):null;}
export function getAnalyticsDataset(tasks:TaskLike[],entries:AnalyticsEntry[],scaleVersions:RatingScaleVersion[] = []):AnalyticsDataset{return {tasks:tasks.map((t,i)=>({...t,color:analyticsColors[i%analyticsColors.length]})),entries,scaleVersions};}
type TaskLike=Pick<AnalyticsTask,'id'|'name'|'options'|'createdAt'|'updatedAt'|'active'|'currentScaleVersionId'|'currentTrendEpochId'>;

export function getRecordingConsistency(tasks: AnalyticsTask[], entries: AnalyticsEntry[], period: {startDate:string;endDate:string}) {
  const start = parseLocalDate(period.startDate), end = parseLocalDate(period.endDate);
  const days: string[] = []; const cursor = new Date(start); while (cursor <= end) { days.push(localDate(cursor)); cursor.setDate(cursor.getDate()+1); }
  const rows = tasks.map(task => { const eligible = days.filter(day => !task.createdAt || day >= task.createdAt.slice(0,10)); const recorded = new Set(entries.filter(entry => entry.taskId===task.id && eligible.includes(entry.localDate)).map(entry=>entry.localDate)); return {taskId:task.id,name:task.name,color:task.color,eligibleDays:eligible.length,recordedDays:recorded.size,coverage:eligible.length?recorded.size/eligible.length:0}; });
  const eligibleDays = rows.reduce((sum,row)=>sum+row.eligibleDays,0); const recordedDays = rows.reduce((sum,row)=>sum+row.recordedDays,0);
  return {rows, eligibleDays, recordedDays, coverage: eligibleDays ? recordedDays/eligibleDays : 0};
}
export function getCombinedRecordingCalendar(tasks: AnalyticsTask[], entries: AnalyticsEntry[], period: {startDate:string;endDate:string}) {
  const start=parseLocalDate(period.startDate), end=parseLocalDate(period.endDate); const cells:{date:string;recorded:number;eligible:number;ratio:number}[]=[]; const cursor=new Date(start);
  while(cursor<=end){const date=localDate(cursor);const eligible=tasks.filter(task=>!task.createdAt||date>=task.createdAt.slice(0,10)).length;const recorded=new Set(entries.filter(entry=>entry.localDate===date).map(entry=>entry.taskId)).size;cells.push({date,recorded,eligible,ratio:eligible?recorded/eligible:0});cursor.setDate(cursor.getDate()+1);} return cells;
}
export function getWeekdayRecordingPattern(tasks: AnalyticsTask[], entries: AnalyticsEntry[], period: {startDate:string;endDate:string}) { return ['Mon','Tue','Wed','Thu','Fri','Sat','Sun'].map((label,index)=>{const dates=entries.filter(entry=>{const d=parseLocalDate(entry.localDate);return entry.localDate>=period.startDate&&entry.localDate<=period.endDate&&(d.getDay()+6)%7===index;}).map(entry=>entry.localDate);return {label,recorded: new Set(dates).size, observations: dates.length};}); }
